name: deploy project
# https://docs.github.com/en/actions/reference/events-that-trigger-workflows
on: [push, workflow_dispatch]
#on:  # multiple event triggers. or [push, workflow_dispatch]
#  - push
#  - workflow_dispatch
jobs:
  test:  # test job
    runs-on: ubuntu-latest
    steps:
      - name: get code
        # https://github.com/marketplace/actions/checkout
        uses: actions/checkout@v3
        #with:  # not required if you don't need to change settings
      # NOT ACTUALLY NEEDED - ubuntu-latest comes with node preinstalled
      - name: Setup Node JS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: install dependencies
        run: npm ci  # better than `npm install` as uses versions from package-lock.json (safer)
      - name: run tests
        run: npm test
  deploy:  # deploy job
    needs: test  # must run after the "test" job
    #needs: [test, job2]  # multiple jobs
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v3
      - name: Setup Node JS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: install dependencies
        run: npm ci
      - name: build project
        run: npm run build
      # would normally upload to webhost here
      - name: deploy
        run: echo "Deploying..."
